import type { CSSProperties } from 'react'
import { RAIL_W } from './constants'

// The single source of truth for the app's look. Kept as a typed style-object map
// (React CSSProperties) rather than a CSS class sheet: a large share of these are
// composed with computed values at render time (pin positions, severity colours,
// active-row halos), so they must stay inline. file-explorer also mixes inline
// `style={{…}}` with its className sheet — this module is the dedicated styles seam.
export const S: Record<string, CSSProperties> = {
  shell: { display: 'flex', height: '100%', minHeight: 0, fontFamily: 'system-ui, sans-serif', color: 'var(--text)' },
  rail: { width: RAIL_W, flexShrink: 0, borderRight: '1px solid var(--border)', background: 'rgba(127,127,127,0.05)', overflowY: 'auto', padding: '18px 18px 24px' },
  railNarrow: { width: '100%', borderRight: 'none', borderBottom: '1px solid var(--border)', maxHeight: '52vh' },
  railHead: { display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '12px' },
  title: { fontSize: '17px', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '9px', flex: 1, minWidth: 0 },
  railCtrls: { display: 'flex', alignItems: 'center', gap: '8px', flexShrink: 0 },
  runChip: { display: 'inline-flex', alignItems: 'center', gap: '5px', padding: '4px 9px', fontSize: '11.5px', fontWeight: 600, borderRadius: '999px', border: '1px solid var(--border)', background: 'var(--card)', color: 'var(--muted)', cursor: 'pointer', flexShrink: 0 },
  readyChip: { borderColor: 'var(--accent)', color: 'var(--accent)' },
  // An in-flight critique in the list: muted so it reads as not-yet-a-result.
  pendingRead: { color: 'var(--muted)', fontStyle: 'italic' },
  railBtn: { display: 'inline-flex', alignItems: 'center', gap: '5px', padding: '5px 10px', fontSize: '12px', fontWeight: 600, borderRadius: '7px', cursor: 'pointer', border: '1px solid var(--border)', background: 'var(--card)', color: 'var(--text)' },
  menu: { position: 'absolute', top: '32px', right: 0, width: '300px', maxHeight: '360px', overflowY: 'auto', background: 'var(--card)', border: '1px solid var(--border)', borderRadius: '10px', padding: '6px', zIndex: 50, boxShadow: '0 10px 30px rgba(0,0,0,.4)' },
  menuItem: { display: 'flex', gap: '9px', alignItems: 'center', padding: '7px', borderRadius: '8px', cursor: 'pointer' },
  menuThumb: { width: '48px', height: '32px', objectFit: 'cover', borderRadius: '5px', border: '1px solid var(--border)', flexShrink: 0 },
  menuRead: { fontSize: '12.5px', fontWeight: 600, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  menuTime: { fontSize: '11px', color: 'var(--muted)', marginTop: '2px' },
  sub: { fontSize: '12.5px', color: 'var(--muted)', lineHeight: 1.45, margin: '0 0 12px' },
  linkBtn: { display: 'inline-flex', alignItems: 'center', gap: '6px', padding: '6px 11px', fontSize: '12.5px', fontWeight: 600, borderRadius: '7px', cursor: 'pointer', border: '1px solid var(--border)', background: 'var(--card)', color: 'var(--text)' },
  sectionH: { fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '.04em', color: 'var(--muted)', margin: '20px 0 8px' },
  listItem: { display: 'flex', gap: '10px', alignItems: 'center', padding: '8px', border: '1px solid var(--border)', borderRadius: '9px', marginBottom: '7px', cursor: 'pointer', background: 'var(--card)' },
  listThumb: { width: '52px', height: '36px', objectFit: 'cover', borderRadius: '5px', border: '1px solid var(--border)', flexShrink: 0 },
  listRead: { fontSize: '12.5px', fontWeight: 600, display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical', overflow: 'hidden' },
  listTime: { fontSize: '11px', color: 'var(--muted)', marginTop: '3px' },
  emptyList: { fontSize: '12.5px', color: 'var(--muted)', border: '1px dashed var(--border)', borderRadius: '10px', padding: '16px', textAlign: 'center' },
  readLine: { fontSize: '15px', fontWeight: 600, lineHeight: 1.4, margin: '0 0 6px' },
  health: { fontSize: '12.5px', color: 'var(--muted)', marginBottom: '10px' },
  chips: { display: 'flex', gap: '7px', flexWrap: 'wrap' },
  chip: { display: 'inline-flex', alignItems: 'center', gap: '5px', padding: '3px 9px', borderRadius: '999px', fontSize: '11.5px', fontWeight: 600, border: '1px solid var(--border)' },
  finding: { overflow: 'hidden', transition: 'background .12s, box-shadow .12s' },
  fRow: { display: 'flex', alignItems: 'flex-start', gap: '9px', padding: '10px 4px', cursor: 'pointer' },
  numBadge: { width: '19px', height: '19px', borderRadius: '999px', color: '#fff', fontSize: '11px', fontWeight: 700, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  fTitle: { fontSize: '13px', fontWeight: 600, flex: 1, lineHeight: 1.35 },
  fMeta: { fontSize: '10.5px', color: 'var(--muted)' },
  sevPill: { display: 'inline-flex', alignItems: 'center', gap: '5px', padding: '2px 7px', borderRadius: '999px', fontSize: '10.5px', fontWeight: 700, border: '1px solid', flexShrink: 0 },
  fBody: { padding: '0 4px 12px 30px', fontSize: '12.5px', lineHeight: 1.5 },
  fLabel: { fontSize: '10.5px', fontWeight: 700, color: 'var(--muted)', marginTop: '8px' },
  ruleBadge: { display: 'inline-flex', alignItems: 'center', padding: '2px 7px', borderRadius: '999px', fontSize: '10.5px', color: 'var(--muted)', border: '1px solid var(--border)' },
  keepItem: { display: 'flex', gap: '8px', alignItems: 'flex-start', fontSize: '12.5px', lineHeight: 1.45, marginBottom: '6px' },
  seeItem: { fontSize: '12px', color: 'var(--muted)', lineHeight: 1.45, marginBottom: '4px' },
  // composer — one centered frame for both the empty and the staged state
  composerMid: { flex: 1, minHeight: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '24px' },
  card: { width: '100%', maxWidth: '660px', display: 'flex', flexDirection: 'column', gap: '14px' },
  cardTitle: { fontSize: '19px', fontWeight: 700, textAlign: 'center', margin: 0 },
  // Fixed-height slot: the text swaps between states without nudging anything below.
  blockedBox: { border: '1px solid var(--error, #e5484d)', background: 'color-mix(in srgb, var(--error, #e5484d) 8%, transparent)', borderRadius: '11px', padding: '13px' },
  blockedSay: { fontSize: '13px', fontWeight: 600, lineHeight: 1.45 },
  blockedHint: { fontSize: '12.5px', color: 'var(--muted)', lineHeight: 1.45, marginTop: '5px' },
  authBox: { marginTop: '11px', paddingTop: '11px', borderTop: '1px solid var(--border)' },
  authCmds: { margin: '8px 0', padding: '9px 11px', background: 'var(--bg)', border: '1px solid var(--border)', borderRadius: '8px', fontSize: '11.5px', fontFamily: 'ui-monospace, monospace', lineHeight: 1.6, whiteSpace: 'pre-wrap', color: 'var(--text)', userSelect: 'text' },
  blockedDetail: { fontSize: '11px', color: 'var(--muted)', fontFamily: 'ui-monospace, monospace', marginTop: '7px', wordBreak: 'break-all', opacity: 0.8 },
  cardSub: { fontSize: '13px', color: 'var(--muted)', textAlign: 'center', margin: '0 0 4px', lineHeight: 1.5, minHeight: '20px', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', flexWrap: 'wrap' },
  clearLink: { border: 'none', background: 'none', padding: 0, color: 'var(--accent)', fontSize: '12.5px', fontWeight: 600, cursor: 'pointer', textDecoration: 'underline' },
  // The drop tile and the staged region are the SAME box: same height, same radius,
  // same position — so adding a screenshot swaps contents without moving the frame.
  dropTile: { height: '232px', boxSizing: 'border-box', border: '2px dashed var(--border)', borderRadius: '14px', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '9px', cursor: 'pointer', color: 'var(--muted)', background: 'rgba(127,127,127,0.03)' },
  stagedRegion: { height: '232px', boxSizing: 'border-box', border: '2px solid var(--border)', borderRadius: '14px', padding: '14px', display: 'flex', flexWrap: 'wrap', gap: '12px', alignContent: 'flex-start', overflowY: 'auto', background: 'rgba(127,127,127,0.03)' },
  orRow: { display: 'flex', alignItems: 'center', gap: '12px', color: 'var(--muted)', fontSize: '11.5px', fontWeight: 600 },
  orLine: { flex: 1, height: '1px', background: 'var(--border)' },
  linkInput: { width: '100%', boxSizing: 'border-box', height: '44px', padding: '0 13px', fontSize: '13px', borderRadius: '10px', border: '1px solid var(--border)', background: 'var(--card)', color: 'var(--text)', fontFamily: 'inherit' },
  // The start action belongs to the whole page, not to the field next to it —
  // so it sits on its own full-width line below both ways in.
  bigStart: { width: '100%', height: '46px', fontSize: '14px', fontWeight: 700, borderRadius: '10px', border: '1px solid var(--accent)', background: 'var(--accent)', color: 'var(--accent-fg)', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: '8px', marginTop: '2px' },
  cardHint: { fontSize: '11.5px', color: 'var(--muted)', textAlign: 'center', lineHeight: 1.5, margin: 0 },
  stagedItem: { width: '168px', position: 'relative' },
  stagedThumb: { width: '168px', height: '112px', borderRadius: '9px', border: '1px solid var(--border)', overflow: 'hidden', background: 'var(--card)' },
  stagedImg: { width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'top', display: 'block' },
  stepChip: { position: 'absolute', top: '6px', left: '6px', minWidth: '20px', height: '20px', padding: '0 6px', borderRadius: '999px', background: 'rgba(0,0,0,.72)', color: '#fff', fontSize: '11px', fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  iconBtn: { width: '22px', height: '22px', borderRadius: '999px', border: '1px solid var(--border)', background: 'var(--card)', color: 'var(--text)', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 0 },
  killBtn: { position: 'absolute', top: '6px', right: '6px', width: '22px', height: '22px', borderRadius: '999px', border: 'none', background: 'rgba(0,0,0,.72)', color: '#fff', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 0 },
  stagedFoot: { display: 'flex', alignItems: 'center', gap: '6px', marginTop: '6px' },
  stagedName: { flex: 1, minWidth: 0, fontSize: '10.5px', color: 'var(--muted)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  addTile: { width: '168px', height: '112px', borderRadius: '9px', border: '1px dashed var(--border)', background: 'transparent', color: 'var(--muted)', cursor: 'pointer', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '5px', fontSize: '11.5px' },
  startOff: { border: '1px solid var(--border)', background: 'var(--card)', color: 'var(--muted)', cursor: 'not-allowed' },
  // scoping — pick what to audit from what was discovered
  scopeNote: { fontSize: '12.5px', color: 'var(--muted)', lineHeight: 1.5, margin: 0 },
  flowCard: { display: 'flex', gap: '10px', alignItems: 'flex-start', padding: '11px 12px', border: '1px solid var(--border)', borderRadius: '10px', background: 'var(--card)', cursor: 'pointer', textAlign: 'left', width: '100%', color: 'var(--text)' },
  flowCardOn: { borderColor: 'var(--accent)', boxShadow: '0 0 0 1px var(--accent)' },
  flowName: { fontSize: '13px', fontWeight: 700 },
  flowWhy: { fontSize: '11.5px', color: 'var(--muted)', marginTop: '3px', lineHeight: 1.45 },
  flowSteps: { fontSize: '11.5px', color: 'var(--muted)', marginTop: '5px' },
  guessTag: { fontSize: '10px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '.05em', color: 'var(--muted)', border: '1px solid var(--border)', borderRadius: '999px', padding: '1px 6px', flexShrink: 0 },
  scopeWrap: { flex: 1, minHeight: 0, overflowY: 'auto', display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '20px 24px 0' },
  scopeCard: { width: '100%', maxWidth: '660px', flex: 1, minHeight: 0, display: 'flex', flexDirection: 'column', gap: '10px' },
  scopeScrollFlex: { border: '1px solid var(--border)', borderRadius: '10px', padding: '6px' },
  scopeFoot: { position: 'sticky', bottom: 0, zIndex: 5, flexShrink: 0, display: 'flex', flexDirection: 'column', gap: '9px',
    paddingTop: '12px', paddingBottom: '14px', marginTop: 'auto', borderTop: '1px solid var(--border)',
    background: 'var(--bg)', boxShadow: '0 -10px 18px -12px rgba(0,0,0,.55)' },
  groupH: { fontSize: '10px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '.05em', color: 'var(--muted)', padding: '8px 8px 4px' },
  pickRow: { display: 'flex', alignItems: 'center', gap: '9px', padding: '6px 8px', borderRadius: '7px', cursor: 'pointer', fontSize: '12.5px' },
  pickRowOff: { opacity: 0.45, cursor: 'not-allowed' },
  grip: { display: 'flex', alignItems: 'center', color: 'var(--muted)', cursor: 'grab', flexShrink: 0, marginLeft: '-2px' },
  pickRowDrag: { opacity: 0.4 },
  pickOrd: { width: '18px', height: '18px', borderRadius: '999px', fontSize: '10px', fontWeight: 700, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, background: 'var(--accent)', color: 'var(--accent-fg)' },
  pickBox: { width: '18px', height: '18px', borderRadius: '5px', border: '1px solid var(--border)', flexShrink: 0 },
  pickWhy: { fontSize: '10.5px', color: 'var(--muted)' },
  // filmstrip (flow mode)
  strip: { display: 'flex', gap: '14px', padding: '14px 18px', borderBottom: '1px solid var(--border)', overflowX: 'auto', flexShrink: 0, alignItems: 'flex-start' },
  thumb: { width: '128px', flexShrink: 0, cursor: 'pointer', border: 'none', background: 'none', padding: 0, textAlign: 'left', color: 'var(--text)' },
  thumbBox: { position: 'relative', width: '128px', height: '84px', borderRadius: '8px', border: '1px solid var(--border)', overflow: 'hidden', background: 'var(--card)' },
  thumbBoxOn: { borderColor: 'var(--accent)', boxShadow: '0 0 0 2px color-mix(in srgb, var(--accent) 40%, transparent)' },
  thumbImg: { width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'top', display: 'block' },
  thumbCount: { position: 'absolute', bottom: '5px', right: '5px', display: 'inline-flex', alignItems: 'center', gap: '4px', padding: '1px 6px', borderRadius: '999px', background: 'rgba(0,0,0,.72)', fontSize: '10.5px', fontWeight: 700, lineHeight: '15px' },
  thumbCap: { fontSize: '11px', marginTop: '7px', color: 'var(--muted)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', fontWeight: 600 },
  stepH: { fontSize: '11px', fontWeight: 700, letterSpacing: '.03em', color: 'var(--muted)', margin: '18px 0 2px', display: 'flex', alignItems: 'center', gap: '8px' },
  stepName: { color: 'var(--text)', fontSize: '12px' },
  stepCount: { marginLeft: 'auto', fontSize: '10.5px', fontWeight: 600 },
  flowBadge: { minWidth: '20px', height: '20px', padding: '0 6px', borderRadius: '999px', color: '#fff', fontSize: '10px', fontWeight: 700, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, marginTop: '1px' },
  // highlight & ask
  askChip: { position: 'fixed', zIndex: 9998, transform: 'translate(-50%, -130%)', display: 'inline-flex', alignItems: 'center', gap: '6px', padding: '6px 11px', fontSize: '12px', fontWeight: 600, borderRadius: '999px', border: '1px solid var(--accent)', background: 'var(--card)', color: 'var(--accent)', cursor: 'pointer', boxShadow: '0 6px 20px rgba(0,0,0,.5)' },
  mark: { background: 'color-mix(in srgb, var(--accent) 22%, transparent)', borderBottom: '1px dashed var(--accent)', borderRadius: '2px', cursor: 'pointer', padding: '0 1px' },
  askPop: { position: 'fixed', zIndex: 9999, width: '360px', maxWidth: 'calc(100vw - 32px)', background: 'var(--card)', border: '1px solid var(--border)', borderRadius: '12px', boxShadow: '0 14px 40px rgba(0,0,0,.55)', padding: '13px', display: 'flex', flexDirection: 'column', gap: '9px' },
  askHead: { display: 'flex', alignItems: 'flex-start', gap: '8px' },
  askIcon: { width: '26px', height: '26px', flexShrink: 0, borderRadius: '7px', border: '1px solid var(--border)', background: 'var(--bg)', color: 'var(--muted)', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 0 },
  askSend: { borderColor: 'var(--accent)', color: 'var(--accent)', width: '36px', height: '36px' },
  askThread: { maxHeight: '260px', overflowY: 'auto', paddingRight: '2px' },
  askQuote: { flex: 1, minWidth: 0, fontSize: '11.5px', color: 'var(--muted)', borderLeft: '2px solid var(--accent)', paddingLeft: '8px', lineHeight: 1.45, maxHeight: '36px', overflow: 'hidden' },
  askInput: { width: '100%', boxSizing: 'border-box', height: '36px', padding: '0 10px', fontSize: '12.5px', borderRadius: '8px', border: '1px solid var(--border)', background: 'var(--bg)', color: 'var(--text)', fontFamily: 'inherit' },
  askAnswer: { fontSize: '12.5px', lineHeight: 1.55, whiteSpace: 'pre-wrap' },
  askRow: { display: 'flex', gap: '7px', alignItems: 'center' },
  askQ: { fontSize: '12px', fontWeight: 700 },
  // canvas
  canvas: { flex: 1, minWidth: 0, minHeight: 0, display: 'flex', flexDirection: 'column', position: 'relative' },
  previewWrap: { flex: 1, minHeight: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '28px', gap: '12px' },
  preview: { position: 'relative', maxWidth: '100%', maxHeight: '100%', borderRadius: '12px', overflow: 'hidden', border: '1px solid var(--border)', boxShadow: '0 8px 40px rgba(0,0,0,.4)', cursor: 'zoom-in' },
  previewImg: { display: 'block', maxWidth: '100%', maxHeight: 'calc(100vh - 140px)' },
  pinMarker: { position: 'absolute', width: '22px', height: '22px', borderRadius: '999px', color: '#fff', fontSize: '11.5px', fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'transform .12s, box-shadow .12s, opacity .12s' },
  pvbar: { fontSize: '11.5px', color: 'var(--muted)', display: 'inline-flex', alignItems: 'center', gap: '6px' },
  dropTitle: { fontSize: '17px', fontWeight: 600, color: 'var(--text)' },
  dropSub: { fontSize: '12.5px', color: 'var(--muted)' },
  // waiting screen — shows what it's working on, how long it's taken, and where it is
  waitWrap: { flex: 1, minHeight: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '18px', padding: '28px' },
  waitCard: { width: '100%', maxWidth: '660px', display: 'flex', flexDirection: 'column', gap: '16px' },
  waitHead: { display: 'flex', alignItems: 'baseline', gap: '10px' },
  waitTitle: { fontSize: '16px', fontWeight: 700, flex: 1 },
  waitRow: { display: 'flex', gap: '10px', flexWrap: 'wrap' },
  waitShot: { position: 'relative', borderRadius: '10px', overflow: 'hidden', border: '1px solid var(--border)', background: 'var(--card)', flexShrink: 0 },
  waitShotImg: { display: 'block', width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'top' },
  sweep: { position: 'absolute', left: 0, right: 0, height: '38%', top: 0, background: 'linear-gradient(180deg, transparent, color-mix(in srgb, var(--accent) 38%, transparent), transparent)' },
  sweepStill: { position: 'absolute', inset: 0, background: 'color-mix(in srgb, var(--accent) 10%, transparent)' },
  waitPlaceholder: { height: '132px', borderRadius: '12px', border: '1px dashed var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px', color: 'var(--muted)', fontSize: '13px', padding: '0 18px', textAlign: 'center' },
  stageList: { display: 'flex', flexDirection: 'column', gap: '9px', margin: 0, padding: 0, listStyle: 'none' },
  stageItem: { display: 'flex', alignItems: 'center', gap: '10px', fontSize: '13px' },
  stageMark: { width: '16px', height: '16px', flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  stageNow: { width: '8px', height: '8px', borderRadius: '999px', background: 'var(--accent)' },
  stagePend: { width: '6px', height: '6px', borderRadius: '999px', border: '1px solid var(--border)' },
  waitFoot: { fontSize: '11.5px', color: 'var(--muted)', lineHeight: 1.5 },

  muted: { fontSize: '13px', color: 'var(--muted)' },
  lbOverlay: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,.86)', zIndex: 9999, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '24px', cursor: 'zoom-out' },
  lbInner: { position: 'relative', display: 'inline-block', maxWidth: '96vw', maxHeight: '92vh', cursor: 'default' },
  lbImg: { display: 'block', maxWidth: '96vw', maxHeight: '92vh', objectFit: 'contain', borderRadius: '8px' },
  lbClose: { position: 'fixed', top: 'calc(var(--safe-area-top, 0px) + 18px)', right: 'calc(env(safe-area-inset-right, 0px) + 18px)', width: '36px', height: '36px', borderRadius: '999px', border: '1px solid var(--border)', background: 'var(--card)', color: 'var(--text)', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 10000 },
  // one transient toast (local)
  toastWrap: { position: 'fixed', bottom: 'calc(env(safe-area-inset-bottom, 0px) + 18px)', right: 'calc(env(safe-area-inset-right, 0px) + 18px)', zIndex: 10001, display: 'flex', flexDirection: 'column', gap: '8px', alignItems: 'flex-end' },
  toast: { padding: '9px 13px', borderRadius: '9px', fontSize: '12.5px', fontWeight: 600, border: '1px solid var(--border)', background: 'var(--card)', color: 'var(--text)', boxShadow: '0 8px 24px rgba(0,0,0,.4)', maxWidth: '320px' },
}
